language: python
sudo: yes
dist: trusty
python:
- '3.3'
branches:
  only:
  - master
install:
- pip install pelican MarkDown
- openssl aes-256-cbc -K $encrypted_8533675f5954_key -iv $encrypted_8533675f5954_iv
  -in id_ed25519.enc -out id_ed25519 -d
- echo $server_fingerprint > ~/.ssh/known_hosts
- chmod 600 id_ed25519
script:
- git submodule update --init --recursive
- make ssh_upload
